[[mgr.prepend_keymap]]
on = "W"
run = "shell -- ln -sf %h ~/.config/background && swww img %h --transition-type grow --transition-pos 0.854,0.977 --transition-duration 2 && hyprpanel setWallpaper %h"
desc = "Set image as wallpaper"
